#-------------------------------------------------------------------------------
#
# ESLint Configuration, http://eslint.org/docs/user-guide/configuring.
#
#-------------------------------------------------------------------------------
---
root: true

extends: "eslint:recommended"

parserOptions:
  ecmaVersion: 6
  impliedStrict: true # All code will be treated as being in strict mode.
  sourceType: "module" # Indicates that we are using ES6 modules.

env:
  es6: true
  mocha: true
  node: true

rules:
  quotes:
    - "error"
    - "double"
