#------------------------------------------------------------------------------
#
# GitHub Actions Test Workflow
#
#------------------------------------------------------------------------------
---
name: master

jobs:
  build:
    runs-on: ubuntu-latest

    on:
      push:
        branches:
          - master

    steps:
      - run: printenv

  publish:
    runs-on: ubuntu-latest

    on: tags

    steps:
      - run: printenv
