#------------------------------------------------------------------------------
#
# GitHub Actions Test Workflow
#
#------------------------------------------------------------------------------
---
name: master

on: tags

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - run: printenv
